_wandb:
    value:
        cli_version: 0.21.0
        e:
            f201znpzp7krqne8e7p7yevawtpb9ckg:
                codePath: testing.py
                codePathLocal: testing.py
                cpu_count: 128
                cpu_count_logical: 256
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "959654658048"
                        used: "827382341632"
                email: timothygao@berkeley.edu
                executable: /home/timothygao/minRL/.venv/bin/python
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-fd84343d-cacc-f0fa-7c1a-28edbaee4d06
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-5eee2ce9-9a54-938f-9200-4ef6acc5873b
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-7b524209-b251-a936-28b1-717d7b019d18
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-3a3a36a0-0446-1bba-2752-50720249c772
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-e4128616-166f-bce6-3f1f-6de980aea862
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-6928ee67-8bef-ecd1-ab78-f4a646f65175
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-60c463f1-f39c-b127-2930-18a91ed82e08
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-3474e719-4a31-605c-2e55-f009d34836f6
                host: dgx6
                memory:
                    total: "2164280131584"
                os: Linux-6.8.0-31-generic-x86_64-with-glibc2.39
                program: /home/timothygao/minRL/testing.py
                python: CPython 3.11.12
                root: /home/timothygao/minRL
                slurm:
                    conf: /etc/slurm/slurm.conf
                startedAt: "2025-08-03T07:00:16.017334Z"
                writerId: f201znpzp7krqne8e7p7yevawtpb9ckg
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 12
                - 45
            "2":
                - 12
                - 45
            "3":
                - 16
            "4": 3.11.12
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
epochs:
    value: 1000
learning_rate:
    value: 1e-06
max_steps:
    value: 500
rollouts_per_epoch:
    value: 50
temperature:
    value: 1.8
